OS-94 Education tab fixes
uclouvain/osis-portal-admission pull request #21
Opened 2021-11-23 14:10 UTC by SebCorbin

2021-11-24 08:44 UTC, BenJneB commented on contrib/forms/education.py
> +
ce double traitement des IntegerFields est obligatoire?
Pas possible de l'éviter avec un blank=True ou autre?

2021-11-25 08:55 UTC, AL9000 requested changes

2021-11-25 08:55 UTC, AL9000 commented on contrib/views/form_tabs/education.py
> +        diploma_type = data.pop("diploma_type", None)
```suggestion
        if not data.pop("got_diploma", None):
            return {}

        diploma_type = data.pop("diploma_type")
```

2021-11-25 13:41 UTC, SebCorbin commented on contrib/views/form_tabs/education.py
> +        diploma_type = data.pop("diploma_type", None)
`got_diploma` est maintenant "requis" dans le sens ou si aucune valeur n'est envoyée, il default à False, ce cas est couvert par https://github.com/uclouvain/osis-portal-admission/pull/21/files#diff-ea5a055ada5f58a1e8cd438770b26e2e0baa7a30e669e42f66e079a0dcb0bba2R102

2021-11-25 13:42 UTC, SebCorbin commented on contrib/forms/education.py
> +
J'ai amélioré les commentaires pour spécifier pourquoi c'est fait, et j'ai implémenté un HourField pour éviter les potentiels effets de bord de `isinstance`

2021-11-25 14:02 UTC, AL9000 approved these changes

2021-11-29 10:13 UTC, BenJneB approved these changes

2021-11-29 10:17 UTC, merged