Check for proposition to be OK before even displaying the submit button
uclouvain/osis-portal-admission pull request #30
Opened 2021-12-15 15:49 UTC by AL9000

2021-12-16 15:15 UTC, SebCorbin requested changes

2021-12-16 15:15 UTC, SebCorbin commented on contrib/views/signatures.py
> +            error.detail += " " + _(proposition_business_exception_error_mapping.get(error.status_code, ""))
`makemessages` ne détectera pas les traductions dynamiques et je préconise de mettre les messages complets (quitte à les reprendre depuis le back) au lieu de faire une concaténation

2021-12-16 15:15 UTC, SebCorbin commented on services/proposition.py
> +    "PROPOSITION-21": "(On 'Cotutelle' tab)",
Utiliser getext ici

2021-12-16 15:15 UTC, SebCorbin commented on templates/admission/doctorate/form_tab_project.html
> +        {% bootstrap_field form.titre_projet label=form.titre_projet.label|add:" *" %}
```suggestion
        {% bootstrap_field form.titre_projet form_group_class="form-group required_field" %}
```
Ainsi que sur toutes les autres, ça te permet de dissocier la traduction du "métier"

2021-12-16 15:15 UTC, SebCorbin commented on templates/admission/doctorate/detail_project.html
> +        {% field_data _("Gantt graph *") admission.graphe_gantt %}
On est pas dans le formulaire, pourquoi le mettre ici ? D'autant plus qu'il risque de ne pas être affiché s'il n'y a pas de valeur

2021-12-23 16:12 UTC, AL9000 commented on templates/admission/doctorate/form_tab_project.html
> +        {% bootstrap_field form.titre_projet label=form.titre_projet.label|add:" *" %}
En effet ! Par contre je vois bien d'autres champs qui incluent cette classe `required_field` mais je n'ai pas de règles css appliquées :/

2021-12-23 17:09 UTC, AL9000 commented on templates/admission/doctorate/form_tab_project.html
> +        {% bootstrap_field form.titre_projet label=form.titre_projet.label|add:" *" %}
j'ai ajouté une petite règle du coup, c'est beaucoup mieux. Reste à savoir si on met toutes ces petites règles dans un fichier CSS propre à admission ?

2022-01-03 10:24 UTC, SebCorbin approved these changes

2022-01-04 14:11 UTC, BenJneB approved these changes

2022-01-04 14:11 UTC, merged